### ISSUE TITLE
In what projection should I provide geometries for encoding?

### ISSUE THREAD

**Issue by ezheidtmann** [mapzen/mapbox-vector-tile#11]
Hi! I'm having some trouble with my vector tiles and I think I'm using the wrong projection. The example shows a WKT geometry in what appears to be latitude & longitude, but the vector tiles spec mentions both spherical mercator and pixel values. So here's my question:

When using `mapbox_vector_tile.encode()`, should I provide geometries in spherical mercator (meters), degrees latitude and longitude, or tile-relative pixels? 

Thanks!

**Comment by rmarianski** [comment]
Tile relative values. We take mercator meters and then scale them to a range of 4096. The scaled values are what we pass to the encoder.

**Comment by ezheidtmann** [comment]
Thanks. Would you consider a PR that documents this?

**Comment by rmarianski** [comment]
Yes, absolutely! :)

I created an issue for it already: https://github.com/mapzen/mapbox-vector-tile/issues/12
