### ISSUE TITLE
Render existing map instance to vector tile

### ISSUE THREAD

**Issue by ekelleyv** [mapzen/mapbox-vector-tile#26]
Essentially I am looking for a python equivalent to this flow in node:
https://github.com/mapnik/node-mapnik/blob/master/test/vector-tile.test.js#L42-L46

I have an existing map instance and would like to just set the map bbox and render to a vector tile protobuf. The current flow for raster tiles looks something like this:

```python
m = Map(tilesize, tilesize)
load_map(m, stylesheet_path)

m.zoom_to_box(bbox)
img = Image(m.width, m.height)
render(m, img, scale)
```

Given that the readme discusses how to do the map->tile projections (https://github.com/mapzen/mapbox-vector-tile#coordinate-transformations-for-encoding), I am assuming this is not particularly straightforward. Any suggestions on the easiest way to get a mapnik Map into the format accepted by the encoder here?

**Comment by zerebubuth** [comment]
Hi! Unfortunately, there's no easy way to do that with this `mapbox-vector-tile` code at the moment, and it looks like [official bindings](https://github.com/mapnik/python-mapnik/issues/27) are still in the works.

However, you could try using [avecado](https://github.com/MapQuest/avecado), which builds some Python bindings for generating vector tiles. The documentation isn't extensive, but the [docs on the `make_vector_tile` function](https://github.com/MapQuest/avecado/blob/master/src/python_module.cpp#L213-L225) seem to suggest that it does something close to what you want.

Hope that helps!

**Comment by ekelleyv** [comment]
Cool, just wanted to make sure I was not missing something super obvious.

I use python datasources, so I can just grab the features from there and do the tile projections myself. Thanks for the quick response.
