### ISSUE TITLE
Encoding process is very slow for non clipped features

### ISSUE THREAD

**Issue by drnextgis** [mapzen/mapbox-vector-tile#28]
Encoding process is very slow for non clipped features but if I use feature clipping by tile bounding box then encoding is performed very fast. Is it expected behavior? I can use clipping, but don't want to see tile bounds which appears in this case. Encoding time: first map - 70s, last - 10s.

![mvt](https://cloud.githubusercontent.com/assets/866124/12457704/ea5174a4-bfc7-11e5-9a40-ad86794c5438.png)

**Comment by rmarianski** [comment]
Unexpected. Even 10 seconds sounds like a long time to me :)

Taking a stab in the dark, are the polygons overly detailed for the zoom level? Are you able to simplify the polygons beforehand before encoding them? If so, I'd imagine that would speed things up significantly.

We haven't done much in the way of trying to improve performance, as things seemed to be "fast enough" thus far. If you are able to profile or pinpoint where the slowness is coming from, we'd certainly be open to discussing what we can do to address it.

**Comment by nvkelso** [comment]
@drnextgis Can you provide more information here?

**Comment by drnextgis** [comment]
After simplification all works like a charm. Sorry for the noise.

**Comment by nvkelso** [comment]
Great to hear this is working for you now! Is your project online so we can check it out?
