### ISSUE TITLE
Tile extent should be 4096 inclusive

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapbox-vector-tile#32]
From the [Mapbox spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers):

```
A layer MUST contain an extent that describes the width and height of the tile in integer
coordinates. The geometries within the Vector Tile MAY extend past the bounds of the 
tile's area as defined by the extent. Geometries that extend past the tile's area as defined 
by extent are often used as a buffer for rendering features that overlap multiple adjacent
tiles.

For example, if a tile has an extent of 4096, coordinate units within the tile refer to 1/4096th
of its square dimensions. A coordinate of 0 is on the top or left edge of the tile, and a 
coordinate of 4096 is on the bottom or right edge. Coordinates from 1 through 4095 
inclusive are fully within the extent of the tile, and coordinates less than 0 or greater than 
4096 are fully outside the extent of the tile.  A point at (1,10) or (4095,10) is within the 
extent of the tile. A point at (0,10) or (4096,10) is on the edge of the extent. A point at 
(-1,10) or (4097,10) is outside the extent of the tile.
```

**Comment by nvkelso** [comment]
Related: #33.

**Comment by loicgasser** [comment]
So they are basically say that the range of values within a tile is `[0, 4096]`, but then the number of possible values over x or y is `4097` and not `4096`. Seems like the doc does not agree with itself.

> For example, if a tile has an extent of 4096, coordinate units within the tile refer to 1/4096th

> A point at (0,10) or (4096,10) is on the edge of the extent.


Which if these statements should we trust?

**Comment by zerebubuth** [comment]
I think it's possible for the doc to agree with itself, if we assume that coordinates are unlike pixels and have zero width. While a bitmap (for example) 10 pixels wide would have positions `[0, 9]` and width 10, this is because the 9th pixel has a width of 1px. A vector tile 10 "pixels" wide would have positions `[0, 10]`, with each coordinate having zero width, but 1px space between them.

One way of thinking about it might be that pixels in raster images index the squares on a sheet of gridded paper, but the coordinates in vector tiles index the lines which separate the squares.

I think it might be less confusing if the doc were (suggestions in italics):

> For example, if a tile has an extent of 4096, _the distance between coordinates_ (_which we call a_ coordinate unit) within the tile refers to 1/4096th of its square dimensions.
>
> A point at (0,10) or (4096,10) is on the edge of the extent.

**Comment by loicgasser** [comment]
@zerebubuth  yes thank you, this makes sense to me now.

**Comment by rmarianski** [comment]
Looks like the issue here is that after scaling, we truncate the point, whereas we'd probably want to round instead.

**Comment by nvkelso** [comment]
Requires Tangram coordination – will there be overlaps and break boundary detection?

**Comment by bcamper** [comment]
Can we put it on a dev server so we can do a visual check?

**Comment by rmarianski** [comment]
Definitely. We haven't implemented the change yet, and will let you know when it's on dev.

**Comment by rmarianski** [comment]
@bcamper these changes should be live on dev now

**Comment by bcamper** [comment]
Looks good.

**Comment by nvkelso** [comment]
I'll also ask the CartoDB folks to look at dev.
