### ISSUE TITLE
Question about quantization in doc

### ISSUE THREAD

**Issue by loicgasser** [mapzen/mapbox-vector-tile#33]
In your doc you metion you have to "pre-quantize" coordinates before passing them to the encoder
using something like:

```python
MVT_EXTENT = 4096
xSpan = maxX - minX
ySpan = maxY - minY
xq = int((x - minX) * MVT_EXTENT / xSpan)
yq = int((y - minY) * MVT_EXTENT / ySpan)
```

but in the offical doc, it says: (https://github.com/mapbox/vector-tile-spec/tree/master/2.1)

```
Geometry data in a Vector Tile is defined in a screen coordinate system. The upper left corner of the tile (as displayed by default) is the origin of the coordinate system. The X axis is positive to the right, and the Y axis is positive downward. Coordinates within a geometry MUST be integers.
```

so downwards for `y` and initial coordinate starts at `(0,0)`.

Shouldn't you change it to:

```python
MVT_EXTENT = 4096
xq = int((x - minX) * MVT_EXTENT / xSpan)
yq = MVT_EXTENT - int((y - minY) * MVT_EXTENT / ySpan)
```

I think that it would help performance if this library could take care of quantization by simply providing bounds and a layer name at initialization. We could then in the same loop that we are extracting the features add them gradually in a functional programming kind of style.

What do you think? I am willing to help out.

**Comment by rmarianski** [comment]
There could be scenarios where the caller knows that the coordinates are already quantized, in which case this step wouldn't be desired.

That being said, I noticed we are a little bit inconsistent because the library assumes that the geometries passed in are in a coordinate system where y is going upward. It always flips the y here: https://github.com/mapzen/mapbox-vector-tile/blob/1412c3f619149670b44efc7f71710edbd1a3e571/mapbox_vector_tile/encoder.py#L217

Maybe it makes sense to have these two assumptions be configuration options?

**Comment by loicgasser** [comment]
> There could be scenarios where the caller knows that the coordinates are already quantized, in which case this step wouldn't be desired.

Yes both should be available according to me.

What distrubs me here that while I am iterating the first time through my features, I need to:
1) Go through all my features to create one dict I then pass to the encoder. (with quantization etc..)
2) And then give it to the encoder. -> Looping 2 times accross features using twice the amount of memory

I'd rather:
1) initialize using layerids
2) add the features within my first external loop (as they come)

I'll give it a try and show you what I mean.

> That being said, I noticed we are a little bit inconsistent because the library assumes that the geometries passed in are in a coordinate system where y is going upward
> Maybe it makes sense to have these two assumptions be configuration options?

Okay, your call I would say adapt the doc if you don't have time.
