### ISSUE TITLE
pip install fails for v0.2.0

### ISSUE THREAD

**Issue by baxford** [mapzen/mapbox-vector-tile#37]
Hi, thanks for this great library!
Since v0.2.0 has been released I'm getting errors from pip install
`
pip install mapbox-vector-tile --no-cache-dir
Collecting mapbox-vector-tile
  Downloading mapbox-vector-tile-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l1/45_7_vv11sjg15_rgtlth0k40000gn/T/pip-build-iHY1UQ/mapbox-vector-tile/setup.py", line 5, in <module>
        with io.open('README.md') as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.md'
`

I've looked at the mapbox-vector-tile-0.2.0.tar.gz file and it doesn't appear to contain README.md which I think is related to the problem.

**Comment by rmarianski** [comment]
That was exactly the problem. I pushed over a 0.2.1 hotfix that should work now.

Thanks for reporting!

**Comment by baxford** [comment]
awesome, that works now thanks!

regards,
Bob Axford


Bob Axford
M: 0413 770 149
E: bob@figjamit.com.au
