### ISSUE TITLE
MultiPolygons are incorrectly encoded as a single Polygon

### ISSUE THREAD

**Issue by bcamper** [mapzen/mapbox-vector-tile#4]
A MultiPolygon is being incorrectly encoded as a single Polygon. It appears the rings of the multipolygon are being flattened into one polygon, so for instance, a multipolygon with two single-ring polygons is being encoded as a single polygon with two rings, which means the second polygon is misinterpreted as a hole in the first polygon.

Instead, since the format doesn't natively support multipolygons, it probably makes the most sense to simply "denormalize" the multipolygon into multiple, individual polygon features, and copy the feature properties from the original multipolygon to each of the new individual polygons.

**Comment by bcamper** [comment]
Top image: correctly encoded multipolygon.
Bottom image: incorrectly encoded multipolygon, which renders as one polygon.

![screen shot 2015-01-30 at 1 02 39 pm](https://cloud.githubusercontent.com/assets/16733/5980954/b18103ee-a883-11e4-9a79-3f70a254290b.png)
![screen shot 2015-01-30 at 1 02 32 pm](https://cloud.githubusercontent.com/assets/16733/5980953/b180008e-a883-11e4-8cce-ee65ddffb636.png)

**Comment by bcamper** [comment]
cc @hkrishna @rmarianski

**Comment by hkrishna** [comment]
Closing this issue. #5 explodes multipolygons
