### ISSUE TITLE
spherical mercator assumption

### ISSUE THREAD

**Issue by pnorman** [mapzen/mapbox-vector-tile#48]
README.md states

> Per the specification, geometries are expected to be in spherical mercator projection before this transformations

The specification is actually projection-agnostic, working only in units within the extent. It's TMS numbering where the projection comes in.

**Comment by zerebubuth** [comment]
I've updated that section of the README in #49 - does that look better now?

**Comment by pnorman** [comment]
:+1:

It also makes some other concepts clearer which I had to step through a couple times to understand.
