### ISSUE TITLE
Decimal + quantize in _round() is substantially slower than round()

### ISSUE THREAD

**Issue by ekelleyv** [mapzen/mapbox-vector-tile#54]
In profiling this library, I have found that a very substantial amount of time is spent in the `_round()` method in encode.py.

Looking through git history, it looks like this change was made for python3 compatibility. I have done very little work with python3, any chance someone could explain the motivation for the change? Aside from even/odd rounding (is this particularly important?), is this functionally different than just calling `round()` on the `val`?
https://github.com/mapzen/mapbox-vector-tile/commit/24ab05b1f8c6093a2606f9a14527492846c590c9

For testing, I used a very large layers object that typically takes a little under 1s to encode. I ran 10 times to reduce noise (hence runtimes in the single digit seconds).

Here is the relevant cProfile output 
```bash
         12019816 function calls (11938319 primitive calls) in 9.586 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.011    0.011    9.586    9.586 profiler.py:1(<module>)
       10    0.001    0.000    9.281    0.928 __init__.py:11(encode)
      120    0.067    0.001    8.544    0.071 encoder.py:60(addFeatures)
    92100    0.227    0.000    3.980    0.000 encoder.py:55(_round)
     8400    0.047    0.000    3.366    0.000 encoder.py:197(addFeature)
     8400    0.029    0.000    3.328    0.000 encoder.py:122(quantize)
     8400    0.179    0.000    3.295    0.000 ops.py:184(transform)
     8400    0.198    0.000    2.617    0.000 encoder.py:360(_geo_encode)
    92100    0.493    0.000    2.348    0.000 decimal.py:2422(quantize)
    26600    0.069    0.000    2.115    0.000 encoder.py:125(fn)
   276306    0.514    0.000    1.459    0.000 decimal.py:515(__new__)
     8400    0.013    0.000    1.261    0.000 encoder.py:97(enforce_winding_order)
     1120    0.012    0.000    1.207    0.001 encoder.py:168(enforce_polygon_winding_order)
```

If we change `_round` to use the built in round like so:
```python
def _round(self, val):
        return round(val)
````

This is the cProfile output: 
```bash
         5916397 function calls (5834900 primitive calls) in 5.245 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.009    0.009    5.245    5.245 profiler.py:1(<module>)
       10    0.000    0.000    4.821    0.482 __init__.py:11(encode)
      120    0.061    0.001    4.102    0.034 encoder.py:60(addFeatures)
     8400    0.042    0.000    2.007    0.000 encoder.py:197(addFeature)
     8400    0.154    0.000    1.306    0.000 encoder.py:360(_geo_encode)
     8400    0.024    0.000    1.122    0.000 encoder.py:122(quantize)
     8400    0.155    0.000    1.094    0.000 ops.py:184(transform)
     8400    0.038    0.000    0.924    0.000 encoder.py:297(_parseGeometry)
       10    0.000    0.000    0.718    0.072 python_message.py:807(SerializeToString)
       10    0.000    0.000    0.682    0.068 python_message.py:821(SerializePartialToString)
 19190/10    0.028    0.000    0.682    0.068 python_message.py:827(InternalSerialize)
   180/10    0.028    0.000    0.682    0.068 encoder.py:744(EncodeRepeatedField)
       13    0.060    0.005    0.550    0.042 __init__.py:1(<module>)
```

Happy to file a PR with this change, but would like to know more about the motivation in case I missed something.

**Comment by rmarianski** [comment]
The change was meant to add consistency across python2/3 versions. The way this was discovered was a test failure in python3 that didn't exist in python2, and the different rounding behavior was the culprit.

How about adding an option to the encoder to allow pluggable rounding behavior? Maybe add an option like `round_fn`, and you can just pass in the default python `round` function directly. I think that by default the behavior should be the current one, which is consistent across python versions just to prevent any confusion. Maybe we should also call this out in the readme so users will be aware of the trade-offs.

Thanks for taking the time to profile!

**Comment by ekelleyv** [comment]
Sounds reasonable to me. Will try and put together a PR today w/ optional round.
