### ISSUE TITLE
reading tiles from file - invalid literal for int() with base 2: 'b10'

### ISSUE THREAD

**Issue by relet** [mapzen/mapbox-vector-tile#7]
I'm not sure if this is a documentation issue or a bug. 

I am trying to decode tiles from this source http://kartverket.maplytic.no/labs/ - for example http://cdn.maplytic.no/kartverket.maplytic.no/tile/sosi_n50,sosi_n250,sosi_n1000,sosi_n2000,sosi_n5000/13/4245/2423.vector.pbf?sosi_n250:zoom=10-11&sosi_n5000:zoom=0-4&sosi_n50:zoom=12-20&sosi_n2000:zoom=5-6&featuretype=%5BOBJTYPE%5D&sosi_n1000:zoom=7-9

These tiles are correctly decoded by mapbox gl. After downloading a tile from the server, I apply the decode method to the data read from file, as in 

    data = open("tile.pbf","rb").read()
    print mapbox_vector_tile.decode(data)

It yields the message 

    invalid literal for int() with base 2: 'b10'

What is the correct way to read a vector tile from file?

**Comment by bcamper** [comment]
@hkrishna would you mind taking a look please?

**Comment by hkrishna** [comment]
@relet thank you for opening this issue and letting us know. This looks like a bug with the mapbox_vector_tile.decode() method. It will need further investigation. 

Closing this for now in favor of #8
